jruby -S script/runner "db/Purchase_description_import.rb"
jruby -S script/runner "db/order_description_import.rb"
jruby -S script/runner "db/Purchases_import.rb"
jruby -S script/runner "db/order_import.rb"
jruby -S script/runner "db/customer_import.rb"
jruby -S script/runner "db/product_import.rb"
jruby -S script/runner "db/employee_import.rb"
jruby -S script/runner "db/supplier_import.rb"